### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by spirituelle** [creativetimofficial/nextjs-material-dashboard#6]
after cloning the app and trying to run "npm install" i am getting this errors

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: nextjs-material-dashboard@1.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.9 || ^15.0.0 || ^16.0.0" from react-chartist@0.14.3
npm ERR! node_modules/react-chartist
npm ERR!   react-chartist@"0.14.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 

https://www.creative-tim.com/new-issue/nextjs-material-dashboard

**If your issue was not created using the app above, it will be closed immediately.**

Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com

**Comment by spirituelle** [comment]
i am using it 😏😑

**Comment by ramoul-b** [comment]
I had the same issue but used this line : 

npm config set legacy-peer-deps true

**Comment by shivamvora** [comment]
I had the same issue you have to do following steps :

1. npm config set legacy-peer-deps true
2. npm i
afterward you can install the packages

**Comment by eadsmedia** [comment]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: nextjs-material-dashboard@1.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.9 || ^15.0.0 || ^16.0.0" from react-chartist@0.14.3
npm ERR! node_modules/react-chartist
npm ERR!   react-chartist@"0.14.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\eAds Media\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\eAds Media\AppData\Local\npm-cache\_logs\2022-08-25T09_06_01_984Z-debug-0.log
